[package]
name = "chord"
version = "0.1.0"
edition = "2024"

[dependencies]
unicode-ident = "1.0"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
tabs_in_doc_comments = "allow"
wildcard_imports = "allow"
